export const URLS = {
  login: "/api/v1/student/login/",
  register: "/api/v1/student/register/",
  studentProfile: "/api/v1/student/profile/",
  olimpiadaQuizList: "/api/v1/quiz/sciences/list/",
  quizTest: "/api/v1/quiz/quizzes/",
  submitAnswers: "/api/v1/quiz/submit-quiz-result/",
  recieveCode: "/api/v1/student/verify-sms/",
  resultQuiz: "/api/v1/quiz/result/list/",
  resendSMSCode: "/api/v1/student/resend-sms-code/",
  forgetPassword: "/api/v1/student/forgot-password/",
  newPassword: "/api/v1/student/reset-password/",
  registerDate: "/api/v1/student/register_date/",
  resendSMSCodeForget: "/api/v1/student/verify-sms-code/",
  faqs: "/faqs/",
  networkings: "/networking/",
  documents: "/olimpiada-about/",
  ofertas: "/nizom/",

  // teacher
  passedRegistration: "/api/v1/student/student_list/",
  passedTest: "/api/v1/quiz/result_pass_exam/",
  passedTestAll: "/api/v1/quiz/result_all/",
  changeRegisterDate: "/api/v1/student/register_date/update/1/",
  teacherQuiz: "/api/v1/quiz/quizzes_teacher/",
  telegramBotUsersList: "/api/v1/quiz/telegram_user/list_view/",
  sendSms: "/api/v1/quiz/send_message_student/",
  activeUsers: "/api/active-users/",
  resultAddStudent: "/api/v1/quiz/result_add_student/",
  addStudent: "/api/v1/quiz/result_pass_exam_status/",
  resultDeleteStudent: "/api/v1/quiz/result_pass_exam/",
  filterStudentCount: "/api/v1/quiz/result_filter_student_count/1/",
  stats: "/api/v1/student/stat/",
};
